---
- hosts: localhost
  remote_user: root
  vars:
      gcp_project: weighty-casing-338809
      gcp_cred_kind: serviceaccount
      gcp_cred_file: /home/cred-kupa.json
      zone: "us-west1-b"
      region: "us-west1"

  tasks:
  #  - name: Create directory
   #   file:
    #    path: /home/Instance
    #    state: directory

    #- name: Clone boxfuse
    #  git:
     #   repo: 'https://github.com/kupa2004/Instance.git'
      #  dest: /home/Instance/
        
   - name: create a disk
     gcp_compute_disk:
         name: 'disk-instance'
         size_gb: 15
         source_image: 'projects/ubuntu-os-cloud/global/images/family/ubuntu-1804-lts'
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: disk
   - name: create a address
     gcp_compute_address:
         name: 'address-instance'
         region: "{{ region }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: address
   - name: create a instance
     gcp_compute_instance:
         state: present
         name: test-vm
         machine_type: f1-micro
         disks:
           - auto_delete: true
             boot: true
             source: "{{ disk }}"
         network_interfaces:
             - network: null # use default
               access_configs:
                 - name: 'External NAT'
                   nat_ip: "{{ address }}"
                   type: 'ONE_TO_ONE_NAT'
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
     register: instance

   - name: Wait for SSH to come up
     wait_for: host={{ address.address }} port=22 delay=10 timeout=60

   - name: Add host to groupname
     add_host: hostname={{ address.address }} groupname=new_instances

- name: package boxfuse
  hosts: new_instances
  connection: ssh
  remote_user: root
  become_user: root
  become: true

  tasks:
    - name: Update system
      apt: update_cache=yes

    - name: Install modules
      apt:
        name: default-jdk
        state: present

    - name: Create directory
      file:
        path: /home/boxfuse-sample-java-war-hello
        state: directory

    - name: Clone boxfuse
      git:
        repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
        dest: /home/boxfuse-sample-java-war-hello/

    - name: install maven
      become: yes
      apt:
        pkg: maven
        state: latest
        update_cache: yes
        cache_valid_time: 3600
      with_items:
        - maven

    - name: Build boxfuse
      command: 'mvn package'
      args:
        chdir: /home/boxfuse-sample-java-war-hello/

    - name: Copy war in jenkins workspace
      copy:
        src: /home/boxfuse-sample-java-war-hello/target/hello-1.0.war
        dest: /var/lib/jenkins/workspace/Cert/hello-1.0.war
